*-qt-tree scripts: New script for removing Qt releases.

diff --git a/Documentation/maintainers/remove-qt-tree b/Documentation/maintainers/remove-qt-tree
--- a/Documentation/maintainers/remove-qt-tree
+++ b/Documentation/maintainers/remove-qt-tree
@@ -1,35 +1,30 @@
 #!/bin/bash
-# custom script for bumping Qt release ebuilds
+# custom script for removing Qt release ebuilds
 # use at your own risk!
 # make sure you take care of any new patches before running this script
 # this does not include the qt meta ebuild
 
 portdir=$(portageq envvar PORTDIR)
-RelVer="4.6.2"
-FinalVer="4.6.3"
+RelVer="4.6.1"
 
 usage() {
 	echo
-	echo "[bump-qt-tree] Bumping Qt ebuilds to ${FinalVer} using ${RelVer} as referense"
-	echo "[bump-qt-tree] and running cvs add, echangelog and repoman manifest"
+	echo "[remove-qt-tree] Removing Qt-${RelVer} ebuilds"
 	echo
 	echo "Options:"
 	echo " -h : displays this message "
 	echo " -f : Does a full bump "
-	echo " -b : Creates the new ebuilds but it doesn't commit them"
-	echo " -r : Runs repoman full only"
+	echo " -r : Removes the ebuilds but doesn't commit them"
 	echo " -c : Run commit phase only"
 	echo 
 }
 
-bump() {
+remove() {
 	cd $portdir/x11-libs/
 	for i in qt-{assistant,core,dbus,demo,gui,multimedia,opengl,phonon,qt3support,script,sql,svg,test,webkit,xmlpatterns} ; do
 		pushd ${i} || exit 'cannot pushd'
-		tomove=$(find '.' -type f -name "${i}-${RelVer}*.ebuild"|head -1)
-		cp ${tomove} ${i}-${FinalVer}.ebuild
-		cvs add ${i}-${FinalVer}.ebuild || exit 'cannot cvs add'
-		echangelog "Version bump to ${FinalVer}" || exit 'cannot echangelog'
+		find '.' -type f -name "${i}-${RelVer}*.ebuild"|xargs cvs remove -f
+		echangelog "Drop Qt-${RelVer}" || exit 'cannot echangelog'
 		repoman manifest || exit 'cannot manifest'
 		popd
 	done
@@ -38,7 +33,7 @@ bump() {
 check() {
 	cd $portdir/x11-libs/
 	echo
-	echo "[bump-qt-release] Checking ebuilds with repoman full - abort if needed"
+	echo "[remove-qt-release] Checking ebuilds with repoman full - abort if needed"
 	echo
 	for i in qt-{assistant,core,dbus,demo,gui,multimedia,opengl,phonon,qt3support,script,sql,svg,test,webkit,xmlpatterns} ; do
 		pushd ${i} || exit 'cannot pushd'
@@ -50,14 +45,14 @@ check() {
 commit() {
 	cd $portdir/x11-libs/
 	echo
-	echo "[bump-qt-release] Doing the actual commit of Qt ${Final} ebuilds"
+	echo "[remove-qt-release] Remove ${RelVer} ebuilds from cvs repo"
 	echo
 	echo "Press 'y' if you are sure about this or 'n' to abort"
 	read choice
 	case "$choice" in
 		y)for i in qt-{assistant,core,dbus,demo,gui,multimedia,opengl,phonon,qt3support,script,sql,svg,test,webkit,xmlpatterns} ; do
 			pushd ${i} || exit 'cannot pushd'
-			repoman commit -m "Qt ${Final} release version bump"
+			repoman commit -m "Removing Qt-${RelVer}"
 			popd
 		done
 		;;
@@ -70,13 +65,11 @@ commit() {
 if [[ "$1" == "-h" ]]; then
 	usage
 elif [[ "$1" == "-f" ]]; then
-	bump
+	remove
 	check
 	commit
 elif [[ "$1" == "-r" ]]; then
-	check
-elif [[ "$1" == "-b" ]]; then
-	bump
+	remove
 elif [[ "$1" == "-c" ]]; then
 	commit
 else usage
